LTXX Approach Boundaries
vatsimnetwork/simaware-tracon-project pull request #209
Opened 2022-09-28 21:29 UTC by gurselalp

Adding all Approach/Proc. Tower TMA's into the file.

Gürsel ALP - 1434943
TRvACC Navigational Director

2022-09-29 03:37 UTC, dirtyformal requested changes
Hi there,

There are multiple entries in your PR where the "name" attribute is not properly formatted, with no space between the station name, and the station type. Please go through and reformat this.

I haven't pulled this into a GIS editor to check the boundaries yet as I'm away from home, but @kmoberg will be able to do that.

2022-09-29 07:37 UTC, kmoberg requested changes

2022-09-29 07:37 UTC, kmoberg commented on TRACONBoundaries.geojson
> +    {"type":"Feature","properties":{"id":"LTCW","prefix":["LTCW"],"suffix":"TWR","name":"Yuksekova Tower/Approach"},"geometry":{"type":"MultiPolygon","coordinates":[[[[44.192728333333328,37.963382222
The file is misformatted and cannot be opened. I suspect this line is the issue as it is missing a comma at the end. Please make sure the file can be opened and resubmit.

2022-09-30 08:21 UTC, kmoberg approved these changes
Incredible work! Well done!

2022-09-30 08:22 UTC, merged