Update TRACONBoundaries.geojson
vatsimnetwork/simaware-tracon-project pull request #214
Opened 2022-10-02 13:52 UTC by ikv20009

2022-10-02 13:54 UTC, maiuswong commented
_TWR prefixes won't work in the way intended here unless you are planning to log-in with UITT_TWR_APP.

2022-10-05 09:43 UTC, kmoberg requested changes
See the inline comments, but this project isn't for tower positions. Please remove them, and tag me once it's done, and I'll review the rest of the submission.

2022-10-05 09:43 UTC, kmoberg commented on TRACONBoundaries.geojson
> +   	{"type":"Feature","properties":{"id":"UIKK","prefix":["UIKK_TWR"],"name":"Kirensk Tower"},"geometry":{"type":"MultiPolygon","coordinates":[[[[108.05889,58.22333],[107.96917,58.22083],[107.88083,5
Note what @maiuswong said in the main conversation thread. This won't work, and isn't intended to work this way. This project is for TRACON/Approach sectors only, not TWR. Adding in a _TWR prefix will not work.

2022-10-05 09:43 UTC, kmoberg commented on TRACONBoundaries.geojson
> +    {"type":"Feature","properties":{"id":"UITT","prefix":["UITT_TWR"],"name":"Ust-Kut Tower"},"geometry":{"type":"MultiPolygon","coordinates":[[[[105.72917,57.30861],[105.64222,57.30611],[105.55583,5
Same issue here. This project isn't for Tower positions.

2022-10-05 09:43 UTC, kmoberg commented on TRACONBoundaries.geojson
> +    {"type":"Feature","properties":{"id":"UNBG","prefix":["UNBG_TWR"],"name":"Gorno-Altaysk Tower"},"geometry":{"type":"MultiPolygon","coordinates":[[[[84.99417,52.38306],[85.36306,51.73500],[86.0500
Same issue here. This project isn't for Tower positions.

2022-10-05 09:43 UTC, kmoberg commented on TRACONBoundaries.geojson
> +    {"type":"Feature","properties":{"id":"UNTT","prefix":["UNTT_TWR"],"name":"Tomsk Tower"},"geometry":{"type":"MultiPolygon","coordinates":[[[[83.88167,57.10167],[83.20000,56.18306],[83.61667,56.100
Same issue here. This project isn't for Tower positions.

2022-10-05 09:43 UTC, kmoberg commented on TRACONBoundaries.geojson
> +    {"type":"Feature","properties":{"id":"UNKY","prefix":["UNKY_TWR"],"name":"Kyzyl Tower"},"geometry":{"type":"MultiPolygon","coordinates":[[[[93.90500,52.15000],[94.05000,51.34667],[94.79167,51.325
Same issue here. This project isn't for Tower positions.

2022-10-05 09:43 UTC, kmoberg commented on TRACONBoundaries.geojson
> +    {"type":"Feature","properties":{"id":"UOTT","prefix":["UOTT_TWR"],"name":"Turukhansk Tower"},"geometry":{"type":"MultiPolygon","coordinates":[[[[87.92806,66.25056],[87.81111,66.24806],[87.69556,6
Same issue here. This project isn't for Tower positions.

2022-10-31 12:44 UTC, closed without merging