Added Riyadh and Jeddah Final Approach TMAs.
vatsimnetwork/simaware-tracon-project pull request #224
Opened 2022-10-11 17:27 UTC by Nestirium

Both OERK/OEJN TMAs have same ids with the final approach TMA. (Not sure if this will affect how SimAware will read it.) But the prefix is different.
One is prefixed with OERK_F
One is prefixed with OEJN_F
According to the documentation, SimAware assumes the suffix as APP if none is provided, so both are approach, none are provided.

2022-10-11 17:29 UTC, Nestirium commented
I think I mistakenly deleted some other boundaries with this pull request because I literally copied and pasted the file from my outdated fork.
Please revert these changes.

2022-10-11 19:31 UTC, kmoberg commented
> I think I mistakenly deleted some other boundaries with this pull request because I literally copied and pasted the file from my outdated fork. Please revert these changes.

That's something you'd need to do on your end to fix your branch.

Also, we're really not trying to show individual sectors, such as the final sector for an airport here - we're displaying the boundary of the TMA in general. The only exception I can imagine of the top of my head are individual, smaller sectors that are regularly staffed with no other TMA filling the remainder of the approach sector. How often is `OEJN` final controllers online with no greater approach controller online?

2022-10-11 19:33 UTC, kmoberg commented
Take a look in the repo and you'll see that this is the case for any major airport such as JFK, ATL, BOS, EGLL. They all just have a single entry showing the entire approach sector online.

2022-10-11 20:54 UTC, Nestirium commented
> 

There is almost never a final approach controller online without a major approach controller.
But if it is possible to display the sector if a final app controller goes online alongside the main approach controller then why not ?
Unless you are trying to follow the same principles as VATSpy data were they do not allow sub-sectorization, then no problem with that, we can just keep the main TMAs.

2022-10-12 14:56 UTC, kmoberg requested changes

2022-10-12 14:56 UTC, kmoberg commented on TRACONBoundaries.geojson
> +    {"type":"Feature","properties":{"id":"OERK","prefix":["OERK_F"],"name":"Riyadh Final"},"geometry":{"type":"MultiPolygon","coordinates":[[[[46.51298034701356,24.86527823549241],[46.60514975769855,
The repo is not designed to display individual sectors and therefor this data is redundant.

2022-10-12 14:56 UTC, kmoberg commented on TRACONBoundaries.geojson
> +    {"type":"Feature","properties":{"id":"OEJN","prefix":["OEJN_F"],"name":"Jeddah Final"},"geometry":{"type":"MultiPolygon","coordinates":[[[[39.09186089624279,21.12009429969131],[39.58502610715921,
The repo is not designed to display individual sectors and therefor this data is redundant.

2022-10-12 15:19 UTC, Nestirium reviewed
No problem, so the only change is correcting the Polygon to a MultiPolygon for OEPS.

2022-10-12 15:19 UTC, closed without merging