DNMM APP Boundary
vatsimnetwork/simaware-tracon-project pull request #238
Opened 2022-11-15 04:53 UTC by defectivepotato

2022-11-18 14:02 UTC, defectivepotato commented
hello guys, any updates on this?

2022-11-26 00:50 UTC, dirtyformal requested changes
Hi there, could you please ensure your commit follows the convention already established within the document, generally following this:
type, properties (id, name, prefix, label coords), geometry.

After this has been fixed, I can take another look. Also, please keep in mind that this is not our sole job, and we do have a day job and other priorities that take precedent before reviewing PRs for this project. 

Thanks!

2022-11-28 02:02 UTC, defectivepotato commented
hello @dirtyformal , I have check and edited it do be in that format.

Cheers,
Josh

2022-11-28 08:43 UTC, kmoberg approved these changes

2022-11-28 08:43 UTC, merged