Add VATBRZ TMAs
vatsimnetwork/simaware-tracon-project pull request #254
Opened 2022-12-15 00:32 UTC by marcelobarretto

## Description
Added TMAs for Brazil

## Motivation and Context
Added TMAs that were not in the files

## How to prove the effect of this PR?
![image](https://user-images.githubusercontent.com/977748/207744466-6c1e56a7-17fc-41c6-80bd-a4fa0e0ebf75.png)

![image](https://user-images.githubusercontent.com/977748/207744504-28bc22bd-1dc1-4822-bbd5-f35e69445447.png)

## Is this a breaking change?
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [X] My change or addition follow the formatting standard of the project.
- [X] I am on the list of approved contributors.

2022-12-15 02:23 UTC, dirtyformal requested changes
Hey Marcelo, thanks for your PR!

It's largely looking very good, but there's a handful of thing's I'd like you to look into before we merge this. It appears that some of your polygons have some points that exist inside the polygon, instead of just around the boundaries. I've attached some images for you!

I also find the boundaries of SBWA quite funny. I assume it's following a river? There's nothing wrong with it, although it'll be entertaining to see how the map displays it!

![SBWK](https://user-images.githubusercontent.com/13634684/207757261-5d17a0a4-281e-47f7-b311-8cc7e244b577.png)
![SBXN-SBWR-SBBS](https://user-images.githubusercontent.com/13634684/207757269-d66d098e-0b9e-400e-89f3-c8ec53a1c18b.png)
![SBWG](https://user-images.githubusercontent.com/13634684/207757314-98ebc6af-de8b-4025-9c9a-5aee04dda5bf.png)

Take a look at those, and we'll merge it after!

Cheers.

2022-12-15 19:04 UTC, marcelobarretto commented
I'll remove the internal lines, didn't see them on my tests.
For SBWA, it does follow a river, that's also the country/fir boundary. I can "simplify" it if it's a problem for the map to display.
Our AIP provides the boundaries as a GeoJson, all we did was "export" with the correct properties/format for SimAware.

2022-12-16 04:45 UTC, dirtyformal approved these changes
Awesome as, thanks for tickling those up for us. Your changes look good to me!

2022-12-22 14:27 UTC, kmoberg approved these changes

2022-12-22 14:27 UTC, merged