VACC Estonia updates (AIRAC 2307)
vatsimnetwork/simaware-tracon-project pull request #314
Opened 2023-07-22 21:33 UTC by mjpikat

- Renamed "Tallin" to "Tallinn" in EETN.json;
- Added sector EETT_H_APP (Tallinn Control, INTOR Feeder sector);
- Added sector EETU_I_TWR (Tartu Information) as its shape is TMA-size.

**All the sectors match current GNG setup**

2023-07-23 10:11 UTC, Soofushka commented
@mjpikat You did a great job! EETU_I_TWR boundaries, unfortunately, wiill not be displayed, you will only see something like this:
![image](https://github.com/vatsimnetwork/simaware-tracon-project/assets/108477923/e112dc00-7e38-441e-9afa-56a83d886f33)

2023-07-24 06:32 UTC, dirtyformal requested changes
As per my comment on EETU_I.json.

2023-07-24 06:32 UTC, dirtyformal commented on Boundaries/EETU/EETU_I.json
Hi there, thanks for contributing. Please note that this project is only for TRACON/TMA boundaries, and not for Towers (even if providing a Procedural service). Please remove this, and then I'll review.

Thanks!

2023-07-24 07:19 UTC, mjpikat commented on Boundaries/EETU/EETU_I.json
> Hi there, thanks for contributing. Please note that this project is only for TRACON/TMA boundaries, and not for Towers (even if providing a Procedural service). Please remove this, and then I'll review.
> 
> Thanks!

Hi Tom! Thanks for the heads-up, I have adjusted the commit now :)

M-J

2023-07-24 09:38 UTC, kmoberg approved these changes

2023-07-24 09:39 UTC, merged