Add SUDU TMA Boundaries
vatsimnetwork/simaware-tracon-project pull request #376
Opened 2024-06-13 15:57 UTC by jks2207

## Description
Add SUDU TMA Boundaries to Simaware

## Motivation and Context
Updating TMA Boundaries on Simaware

## How to prove the effect of this PR?
![Screenshot 2024-06-13 175615](https://github.com/vatsimnetwork/simaware-tracon-project/assets/160325656/4782229f-db8a-4019-be6f-256908d0e2ca)

## Checklist

- [x] My change or addition follow the formatting standard of the project.
- [x] I am on the list of approved contributors.

2024-06-17 11:01 UTC, kmoberg approved these changes

2024-09-11 07:48 UTC, dirtyformal requested changes
Hi there, thanks for your contribution.

Please modify your PR so that `SUDU.json` is nested within a folder named `SUDU`, then I'll be happy to merge your request.

2024-10-04 09:51 UTC, dirtyformal commented
Hi @jks2207 - can you please make the changes that I've requested above?

2024-10-04 09:55 UTC, jks2207 commented
Sorry Tom I forgot to answer last time. We decided to discontinue the request with the introduction of the polygon of Vatsim Radar which has the same data as this PR.

2024-10-04 09:55 UTC, closed without merging