Add LGGG TMAs and MTMAs
vatsimnetwork/simaware-tracon-project pull request #399
Opened 2024-11-05 12:47 UTC by Ioannis-G

## Description
Added boundaries for the 24 total TMAs and Military TMAs inside Athinai FIR.

## Motivation and Context
This change will add boundaries for the approach positions of LGGG FIR

## How to prove the effect of this PR?
![Στιγμιότυπο οθόνης 2024-11-05 133601](https://github.com/user-attachments/assets/1b683871-1f73-4374-b73d-7e3b39513c99)

Chart ENR 6.1 depicts all TMA and MTMA boundaries:
![image](https://github.com/user-attachments/assets/8436dd21-6b94-406e-953e-4ba25bbd8a5c)
![image](https://github.com/user-attachments/assets/b56c98f8-708b-459a-9105-c947df8d999b)
![image](https://github.com/user-attachments/assets/b495d2fe-ab6c-4eae-bd5a-f9a1cb4168dd)

PDF Version: 
[LG_ENR_6_1_en.pdf](https://github.com/user-attachments/files/17632447/LG_ENR_6_1_en.pdf) (AIRAC 2412)

## Additional info
Detailed TMA and MTMA definitions can be found at chart ENR 2.1:
[LG_ENR_2_1_en.pdf](https://github.com/user-attachments/files/17632628/LG_ENR_2_1_en.pdf)

## Is this a breaking change?

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My change or addition follow the formatting standard of the project.
- [x] I am on the list of approved contributors.

2024-11-05 14:44 UTC, Ioannis-G commented
LGIR TMA after correction:

![image](https://github.com/user-attachments/assets/23f65e8b-45dd-4b4f-8b45-da0ec12ba4a7)

2024-11-05 19:25 UTC, ziplock1 commented
Wonderful!

2024-11-12 05:19 UTC, dirtyformal requested changes
Thanks for your commit! 

There are a few boundaries that don't line up with eachother, despite your source material showing it. Could you please fix up these boundaries:

**LGKR / LGPZ**: 
![image](https://github.com/user-attachments/assets/ab86bace-6ece-49e2-9719-853b82b88b06)

**LGBL / LGSK / LGTG / LGSY**:
![image](https://github.com/user-attachments/assets/cfc84880-ad7f-4d07-bfe3-5d28e4e4146b)

**LGSA / LGIR**:

![image](https://github.com/user-attachments/assets/6d6e1c13-6e84-4bd2-a09b-d4230bd5db30)

Thanks!

2024-12-07 10:31 UTC, dirtyformal approved these changes
Looks good to me! Thanks for making those changes!

2025-01-25 23:10 UTC, merged